[package]
name = "rs_demo"
version = "0.1.0"
edition = "2021"

[dependencies]
futures = "0.3.26"
tokio = { version = "1.25.0", features = ["rt", "sync", "time", "macros"] }
tokio-util = { version = "0.7.6", features = ["time"] }
